<?php

/** @var array<string, array{insights?: list<array<string, mixed>>, extra_insights?: list<array<string, mixed>>, slug_insights?: array<string, list<string>>}> $PROFILE_OVERRIDES */
$PROFILE_OVERRIDES = [
    'hihagiang' => [
        'extra_insights' => [
            [
                'slug' => 'cuoi-tuan-ha-noi',
                'code' => 'weekend-hanoi',
                'vi' => 'Cuoi tuan tu Ha Noi',
                'en' => 'Weekend from Hanoi',
                'subtitle_vi' => 'Loop 2-3 ngay, xe dem HN — sweet spot dan van phong.',
                'subtitle_en' => '2-3 day loops, overnight bus from Hanoi.',
                'seo_vi' => 'Bo loc intent khach Ha Noi — khong trung danh muc GEO tung huyen.',
                'seo_en' => 'Intent filter for Hanoi weekenders — not per-district GEO pages.',
                'slugs' => ['ha-giang-loop-3-ngay-2-dem', 'quan-ba-co-tien-2-ngay-1-dem', 'dong-van-homestay-2-ngay', 'hoang-su-phi-2-ngay-1-dem', 'bac-me-thac-ba-2-ngay'],
            ],
            [
                'slug' => 'gia-dinh-nhom-nho',
                'code' => 'gia-dinh-nhom-nho',
                'vi' => 'Gia dinh & nhom nho',
                'en' => 'Family & small group',
                'subtitle_vi' => 'O to an toan, lich nhe — khong bat buoc xe may.',
                'subtitle_en' => 'Safe car travel, light pace, no motorbike required.',
                'seo_vi' => 'Phan khuc gia dinh/nhom ban — loc theo nhu cau, khong theo vung.',
                'seo_en' => 'Family/friends segment — need-based filter, not regional.',
                'slugs' => ['quan-ba-co-tien-2-ngay-1-dem', 'ha-giang-loop-4-ngay-3-dem', 'thanh-pho-ha-giang-1-ngay', 'yen-minh-rung-thong-1-ngay'],
            ],
        ],
        'slug_insights' => [
            'ha-giang-loop-3-ngay-2-dem' => ['weekend-hanoi', 'loop-cao-nguyen', 'homestay-dan-toc'],
            'ha-giang-loop-4-ngay-3-dem' => ['loop-cao-nguyen', 'homestay-dan-toc', 'gia-dinh-nhom-nho'],
            'ha-giang-loop-5-ngay-4-dem' => ['loop-cao-nguyen', 'homestay-dan-toc'],
            'ha-giang-loop-xe-may-3-ngay' => ['xe-may', 'loop-cao-nguyen'],
            'quan-ba-co-tien-2-ngay-1-dem' => ['weekend-hanoi', 'gia-dinh-nhom-nho'],
            'dong-van-homestay-2-ngay' => ['weekend-hanoi', 'homestay-dan-toc'],
            'hoang-su-phi-2-ngay-1-dem' => ['weekend-hanoi'],
            'mua-tam-giac-mach-3-ngay' => ['mua-hoa', 'loop-cao-nguyen'],
            'mua-hoa-dao-3-ngay' => ['mua-hoa'],
            'thanh-pho-ha-giang-1-ngay' => ['gia-dinh-nhom-nho'],
            'yen-minh-rung-thong-1-ngay' => ['gia-dinh-nhom-nho'],
        ],
    ],
    'hisapa' => [
        'slug_insights' => [
            'sapa-2n1d-cuoi-tuan-ha-noi' => ['cuoi-tuan-ha-noi', 'fansipan'],
            'sapa-3n2d-tong-quan' => ['fansipan', 'gia-dinh'],
            'sapa-2n1d-lang-man' => ['cuoi-tuan-ha-noi', 'cap-doi'],
            'city-tour-sapa-1-ngay' => [],
            'fansipan-cap-treo-1-ngay' => ['fansipan'],
            'muong-hoa-trek-homestay-2n1d' => ['trekking-homestay'],
            'food-tour-am-thuc-sapa' => ['am-thuc'],
            'gia-dinh-sapa-2n1d' => ['gia-dinh'],
            'ha-noi-sapa-tour-ngay' => ['cuoi-tuan-ha-noi'],
            'sapa-4n3d-kham-pha-sau' => ['trekking-homestay'],
            'photo-tour-ruong-bac-thang' => ['cap-doi'],
        ],
    ],
    'hitamdao' => [
        'slug_insights' => [
            'tam-dao-2n1d-cuoi-tuan-ha-noi' => ['cuoi-tuan-ha-noi'],
            'tam-dao-3n2d-tong-quan' => ['gia-dinh'],
            'tam-dao-2n1d-lang-man' => ['cuoi-tuan-ha-noi', 'suong-mu-lang-man'],
            'trekking-vqg-tam-dao-1-ngay' => ['trekking-vqg'],
            'food-tour-am-thuc-tam-dao' => ['am-thuc-doi-ga'],
            'gia-dinh-tam-dao-2n1d' => ['gia-dinh'],
            'team-building-tam-dao-2n1d' => ['team-building-mice', 'trekking-vqg'],
            'ha-noi-tam-dao-tour-ngay' => ['cuoi-tuan-ha-noi'],
            'tam-dao-4n3d-kham-pha-sau' => ['trekking-vqg'],
            'photo-tour-suong-mu-tam-dao' => ['suong-mu-lang-man'],
        ],
    ],
    'himuine' => [
        'extra_insights' => [
            [
                'slug' => 'honeymoon-bien',
                'code' => 'honeymoon',
                'vi' => 'Trang mat & cap doi',
                'en' => 'Honeymoon & couples',
                'subtitle_vi' => 'Resort 4-5*, sunset cruise.',
                'subtitle_en' => '4-5* resort, sunset cruise.',
                'seo_vi' => 'Mini honeymoon bien nong gan SGN.',
                'seo_en' => 'Hot beach mini honeymoon near Saigon.',
                'slugs' => ['honeymoon-mui-ne-3n2d'],
            ],
        ],
        'slug_insights' => [
            'tour-ngay-doi-cat-suoi-tien' => ['doi-cat'],
            'jeep-doi-cat-do-sunrise' => ['doi-cat'],
            'jeep-doi-cat-trang-bau-trang' => ['doi-cat'],
            'suoi-tien-nua-ngay' => ['doi-cat'],
            'lang-chai-mui-ne-sang' => ['lang-chai'],
            'ham-tien-beach-kite-culture' => ['kite-surf'],
            'mui-ne-2n1d-resort-dunes' => ['gia-dinh', 'doi-cat'],
            'mui-ne-3n2d-kite-surf-package' => ['kite-surf'],
            'sai-gon-mui-ne-2n1d-weekend' => ['combo', 'gia-dinh'],
            'sai-gon-mui-ne-tour-ngay' => ['combo', 'doi-cat'],
            'gia-dinh-mui-ne-2n1d' => ['gia-dinh'],
            'honeymoon-mui-ne-3n2d' => ['honeymoon'],
            'food-tour-phan-thiet-dem' => ['lang-chai'],
            'tour-ngay-private-jeep-dunes' => ['doi-cat'],
            'da-lat-mui-ne-3n2d' => ['combo'],
        ],
    ],
];
