<?php
/**
 * One-off: rebuild tour theme categories + travel_styles for all hub projects (except vitravel).
 * Run: php project/rebuild_tour_themes.php
 */

declare(strict_types=1);

$profiles = [
    'hihagiang' => [
        'hub' => 'thanh-pho-ha-giang',
        'insights' => [
            ['slug' => 'cuoi-tuan-ha-noi', 'code' => 'weekend-hanoi', 'vi' => 'Cuối tuần từ Hà Nội', 'en' => 'Weekend from Hanoi',
                'subtitle_vi' => 'Loop 2–3 ngày, xe đêm HN — sweet spot dân văn phòng.', 'subtitle_en' => '2–3 day loops, overnight bus from Hanoi — office-worker sweet spot.',
                'seo_vi' => 'Bộ lọc intent: khách Hà Nội thoát phố cuối tuần, không trùng danh mục GEO từng huyện.',
                'seo_en' => 'Intent filter for Hanoi weekenders — distinct from per-district GEO category pages.',
                'slugs' => ['ha-giang-loop-3-ngay-2-dem', 'quan-ba-co-tien-2-ngay-1-dem', 'dong-van-homestay-2-ngay', 'hoang-su-phi-2-ngay-1-dem', 'bac-me-thac-ba-2-ngay']],
            ['slug' => 'loop-cao-nguyen', 'code' => 'karst-loop', 'vi' => 'Loop cao nguyên đá', 'en' => 'Karst plateau loop',
                'subtitle_vi' => 'Công viên địa chất UNESCO — hành trình signature Hà Giang.', 'subtitle_en' => 'UNESCO geopark — Ha Giang\'s signature journey.',
                'seo_vi' => 'Chủ đề theo chương trình loop, không trùng trang zone Đồng Văn/Mèo Vạc.', 'seo_en' => 'Program-based loop theme — not a duplicate of Dong Van/Meo Vac zone pages.',
                'slugs' => ['ha-giang-loop-3-ngay-2-dem', 'ha-giang-loop-4-ngay-3-dem', 'ha-giang-loop-5-ngay-4-dem']],
            ['slug' => 'homestay-dan-toc', 'code' => 'ethnic-homestay', 'vi' => 'Homestay dân tộc', 'en' => 'Ethnic homestays',
                'subtitle_vi' => 'H\'Mông, Dao, Tày — ăn ngủ cùng gia đình bản địa.', 'subtitle_en' => 'Hmong, Dao, Tay — eat and sleep with local families.',
                'seo_vi' => 'Trải nghiệm văn hoá theo insight khách, khác danh mục GEO homestay từng vùng.', 'seo_en' => 'Cultural experience by guest intent — not a GEO zone duplicate.',
                'slugs' => ['dong-van-homestay-2-ngay', 'ha-giang-loop-3-ngay-2-dem', 'ha-giang-loop-4-ngay-3-dem', 'ha-giang-loop-5-ngay-4-dem']],
            ['slug' => 'loop-xe-may', 'code' => 'motorbike-loop', 'vi' => 'Loop xe máy', 'en' => 'Motorbike loop',
                'subtitle_vi' => 'Tự lái với xe hỗ trợ và leader an toàn.', 'subtitle_en' => 'Self-ride with support van and safety leader.',
                'seo_vi' => 'Đặc tính hình thức di chuyển — không phải trang danh mục Mèo Vạc.', 'seo_en' => 'Transport style filter — not the Meo Vac GEO category page.',
                'slugs' => ['ha-giang-loop-xe-may-3-ngay']],
            ['slug' => 'mua-hoa-dac-biet', 'code' => 'flower-season', 'vi' => 'Mùa hoa đặc biệt', 'en' => 'Flower seasons',
                'subtitle_vi' => 'Tam giác mạch (10–11), hoa đào Tết (1–2).', 'subtitle_en' => 'Buckwheat (Oct–Nov), peach blossom Tet (Jan–Feb).',
                'seo_vi' => 'Insight mùa vụ — đặt sớm 3–4 tuần peak season.', 'seo_en' => 'Seasonal insight — book 3–4 weeks ahead in peak season.',
                'slugs' => ['mua-tam-giac-mach-3-ngay', 'mua-hoa-dao-3-ngay']],
            ['slug' => 'gia-dinh-nhom-nho', 'code' => 'family-small-group', 'vi' => 'Gia đình & nhóm nhỏ', 'en' => 'Family & small group',
                'subtitle_vi' => 'Ô tô an toàn, lịch nhẹ, không bắt buộc xe máy.', 'subtitle_en' => 'Safe car travel, light pace, no motorbike required.',
                'seo_vi' => 'Phân khúc khách gia đình/nhóm bạn — lọc theo nhu cầu, không theo vùng.', 'seo_en' => 'Family/friends segment — need-based filter, not regional.',
                'slugs' => ['quan-ba-co-tien-2-ngay-1-dem', 'ha-giang-loop-4-ngay-3-dem', 'thanh-pho-ha-giang-1-ngay', 'yen-minh-rung-thong-1-ngay']],
        ],
        'slug_insights' => [
            'ha-giang-loop-3-ngay-2-dem' => ['weekend-hanoi', 'karst-loop', 'ethnic-homestay'],
            'ha-giang-loop-4-ngay-3-dem' => ['karst-loop', 'ethnic-homestay', 'family-small-group'],
            'ha-giang-loop-5-ngay-4-dem' => ['karst-loop', 'ethnic-homestay', '5-plus-days'],
            'ha-giang-loop-xe-may-3-ngay' => ['motorbike-loop', 'karst-loop'],
            'quan-ba-co-tien-2-ngay-1-dem' => ['weekend-hanoi', 'family-small-group'],
            'ma-pi-leng-nho-que-1-ngay' => ['day-trip'],
            'dong-van-homestay-2-ngay' => ['weekend-hanoi', 'ethnic-homestay'],
            'hoang-su-phi-2-ngay-1-dem' => ['weekend-hanoi'],
            'mua-tam-giac-mach-3-ngay' => ['flower-season', 'karst-loop'],
            'mua-hoa-dao-3-ngay' => ['flower-season'],
            'thanh-pho-ha-giang-1-ngay' => ['family-small-group'],
            'yen-minh-rung-thong-1-ngay' => ['family-small-group'],
            'ha-giang-sapa-5-ngay' => ['5-plus-days'],
            'ha-giang-cao-bang-6-ngay' => ['5-plus-days'],
            'food-tour-ha-giang-toi' => ['day-trip'],
            'bac-me-thac-ba-2-ngay' => ['weekend-hanoi'],
        ],
    ],
    'hisapa' => [
        'hub' => 'thi-tran-sapa',
        'insights' => [
            ['slug' => 'cuoi-tuan-ha-noi', 'code' => 'weekend-hanoi', 'vi' => 'Cuối tuần từ Hà Nội', 'en' => 'Weekend from Hanoi',
                'subtitle_vi' => 'Tàu đêm SP/CH, limo 5–6h — 2N1D & tour ngày.', 'subtitle_en' => 'Overnight SP/CH train or 5–6h limo — 2N1D & day trips.',
                'seo_vi' => 'Intent thoát phố HN (~320km) — không trùng zone GEO thị trấn.', 'seo_en' => 'Hanoi escape intent (~320km) — not the town GEO zone page.',
                'slugs' => ['sapa-2n1d-cuoi-tuan-ha-noi', 'ha-noi-sapa-tour-ngay', 'sapa-2n1d-lang-man']],
            ['slug' => 'trekking-homestay', 'code' => 'trekking-homestay', 'vi' => 'Trekking & homestay', 'en' => 'Trekking & homestay',
                'subtitle_vi' => 'Lao Chai, Ta Van, Bản Hồ — ngủ nhà dân.', 'subtitle_en' => 'Lao Chai, Ta Van, Ban Ho — village stays.',
                'seo_vi' => 'Adventure intent — HLV bản địa, tôn trọng phong tục bản làng.', 'seo_en' => 'Adventure intent — local guides, respect village customs.',
                'slugs' => ['muong-hoa-trek-homestay-2n1d', 'sapa-4n3d-kham-pha-sau']],
            ['slug' => 'fansipan-cable-car', 'code' => 'fansipan', 'vi' => 'Fansipan & cáp treo', 'en' => 'Fansipan & cable car',
                'subtitle_vi' => 'Đỉnh 3143m, tàu Mười Mây — không trek nặng.', 'subtitle_en' => '3143m summit, Muoi May train — no heavy trekking.',
                'seo_vi' => 'Chủ đề trải nghiệm đỉnh núi — khác danh mục zone Fansipan Sun World.', 'seo_en' => 'Summit experience theme — distinct from Fansipan Sun World GEO page.',
                'slugs' => ['fansipan-cap-treo-1-ngay', 'sapa-2n1d-cuoi-tuan-ha-noi', 'sapa-3n2d-tong-quan']],
            ['slug' => 'am-thuc-dac-san', 'code' => 'food-culture', 'vi' => 'Ẩm thực đặc sản', 'en' => 'Local cuisine',
                'subtitle_vi' => 'Thắng cố, cá hồi, BBQ, rượu ngô.', 'subtitle_en' => 'Thang co, salmon hotpot, BBQ, corn wine.',
                'seo_vi' => 'Foodie intent — tour ẩm thực & chợ đêm.', 'seo_en' => 'Foodie intent — cuisine tours and night market.',
                'slugs' => ['food-tour-am-thuc-sapa']],
            ['slug' => 'cap-doi-lang-man', 'code' => 'romantic', 'vi' => 'Cặp đôi & lãng mạn', 'en' => 'Couples & romantic',
                'subtitle_vi' => 'Ham Rong biển mây, Mường Hoa, photo tour.', 'subtitle_en' => 'Ham Rong cloud sea, Muong Hoa, photo tour.',
                'seo_vi' => 'Mini trăng mật không cần bay xa từ HN.', 'seo_en' => 'Mini honeymoon without flying far from Hanoi.',
                'slugs' => ['sapa-2n1d-lang-man', 'photo-tour-ruong-bac-thang']],
            ['slug' => 'gia-dinh-tre-em', 'code' => 'family', 'vi' => 'Gia đình có trẻ em', 'en' => 'Family with kids',
                'subtitle_vi' => 'Fansipan cáp treo, lịch nhẹ — không trek nặng.', 'subtitle_en' => 'Cable car Fansipan, light pace — no heavy trekking.',
                'seo_vi' => 'Phân khúc gia đình — ưu tiên cáp treo & tàu hoả.', 'seo_en' => 'Family segment — cable car and mountain train first.',
                'slugs' => ['gia-dinh-sapa-2n1d', 'sapa-3n2d-tong-quan']],
        ],
        'slug_insights' => [
            'sapa-2n1d-cuoi-tuan-ha-noi' => ['weekend-hanoi', 'fansipan'],
            'sapa-3n2d-tong-quan' => ['fansipan', 'family'],
            'sapa-2n1d-lang-man' => ['weekend-hanoi', 'romantic'],
            'city-tour-sapa-1-ngay' => ['day-trip'],
            'fansipan-cap-treo-1-ngay' => ['fansipan'],
            'muong-hoa-trek-homestay-2n1d' => ['trekking-homestay'],
            'cat-cat-y-linh-ho-nua-ngay' => ['day-trip'],
            'thac-bac-thac-tinh-yeu-1-ngay' => ['day-trip'],
            'food-tour-am-thuc-sapa' => ['food-culture'],
            'gia-dinh-sapa-2n1d' => ['family'],
            'ha-noi-sapa-tour-ngay' => ['weekend-hanoi'],
            'sapa-4n3d-kham-pha-sau' => ['trekking-homestay', '4n3d'],
            'combo-sapa-bac-ha-3n2d' => ['3n2d'],
            'photo-tour-ruong-bac-thang' => ['romantic'],
        ],
    ],
    'hitamdao' => [
        'hub' => 'trung-tam-thi-tran',
        'insights' => [
            ['slug' => 'cuoi-tuan-ha-noi', 'code' => 'weekend-hanoi', 'vi' => 'Cuối tuần từ Hà Nội', 'en' => 'Weekend from Hanoi',
                'subtitle_vi' => 'Limousine 2–2.5h — 2N1D & tour ngày.', 'subtitle_en' => '2–2.5h limo — 2N1D & day trips.',
                'seo_vi' => 'Intent thoát phố HN (~80km) — không trùng zone GEO thị trấn.', 'seo_en' => 'Hanoi escape (~80km) — not the town GEO zone page.',
                'slugs' => ['tam-dao-2n1d-cuoi-tuan-ha-noi', 'ha-noi-tam-dao-tour-ngay', 'tam-dao-2n1d-lang-man']],
            ['slug' => 'suong-mu-lang-man', 'code' => 'fog-romantic', 'vi' => 'Sương mù & lãng mạn', 'en' => 'Mist & romance',
                'subtitle_vi' => 'Resort sương, Cầu Mây, photo tour.', 'subtitle_en' => 'Mist resort, Cloud Bridge, photo tour.',
                'seo_vi' => 'Mini trăng mật núi rừng gần HN.', 'seo_en' => 'Forest hill mini honeymoon near Hanoi.',
                'slugs' => ['tam-dao-2n1d-lang-man', 'photo-tour-suong-mu-tam-dao']],
            ['slug' => 'trekking-vqg', 'code' => 'trekking-nature', 'vi' => 'Trekking & VQG', 'en' => 'Trekking & national park',
                'subtitle_vi' => 'Rừng thông, chim, picnic — HLV địa phương.', 'subtitle_en' => 'Pine forest, birds, picnic — local guides.',
                'seo_vi' => 'Adventure intent — không xả rác trong rừng.', 'seo_en' => 'Adventure intent — leave no trace in the forest.',
                'slugs' => ['trekking-vqg-tam-dao-1-ngay', 'tam-dao-4n3d-kham-pha-sau', 'team-building-tam-dao-2n1d']],
            ['slug' => 'am-thuc-doi-ga', 'code' => 'food-culture', 'vi' => 'Ẩm thực gà đồi & suối cá', 'en' => 'Hill chicken & fish stream',
                'subtitle_vi' => 'Gà đồi, suối cá, chay tỏi, rượu mật ong.', 'subtitle_en' => 'Hill chicken, fish stream, garlic veg, honey wine.',
                'seo_vi' => 'Foodie intent Tam Đảo — không trùng zone suối cá GEO.', 'seo_en' => 'Tam Dao foodie intent — not the fish-stream GEO page.',
                'slugs' => ['food-tour-am-thuc-tam-dao']],
            ['slug' => 'team-building-mice', 'code' => 'team-building', 'vi' => 'Team-building & MICE', 'en' => 'Team building & MICE',
                'subtitle_vi' => 'Resort + game rừng + gala — doanh nghiệp HN.', 'subtitle_en' => 'Resort + forest games + gala — Hanoi corporates.',
                'seo_vi' => 'Phân khúc doanh nghiệp — limo đoàn, phòng họp.', 'seo_en' => 'Corporate segment — group limo, meeting rooms.',
                'slugs' => ['team-building-tam-dao-2n1d']],
            ['slug' => 'gia-dinh-tre-em', 'code' => 'family', 'vi' => 'Gia đình có trẻ em', 'en' => 'Family with kids',
                'subtitle_vi' => 'Thác & suối cá — lịch nhẹ, không trek nặng.', 'subtitle_en' => 'Falls & fish stream — light pace, no heavy trekking.',
                'seo_vi' => 'Ưu tiên suối cá & phố đi bộ cho trẻ nhỏ.', 'seo_en' => 'Fish stream and town walks for young kids.',
                'slugs' => ['gia-dinh-tam-dao-2n1d', 'tam-dao-3n2d-tong-quan']],
        ],
        'slug_insights' => [
            'tam-dao-2n1d-cuoi-tuan-ha-noi' => ['weekend-hanoi'],
            'tam-dao-3n2d-tong-quan' => ['family'],
            'tam-dao-2n1d-lang-man' => ['weekend-hanoi', 'fog-romantic'],
            'city-tour-tam-dao-1-ngay' => ['day-trip'],
            'thac-bac-thac-dai-1-ngay' => ['day-trip'],
            'cau-may-sky-walk-nua-ngay' => ['day-trip'],
            'trekking-vqg-tam-dao-1-ngay' => ['trekking-nature'],
            'food-tour-am-thuc-tam-dao' => ['food-culture'],
            'gia-dinh-tam-dao-2n1d' => ['family'],
            'team-building-tam-dao-2n1d' => ['team-building', 'trekking-nature'],
            'ha-noi-tam-dao-tour-ngay' => ['weekend-hanoi'],
            'tam-dao-4n3d-kham-pha-sau' => ['trekking-nature', '4n3d'],
            'photo-tour-suong-mu-tam-dao' => ['fog-romantic'],
            'combo-tam-dao-ninh-binh-3n2d' => ['3n2d'],
        ],
    ],
    'himuine' => [
        'hub' => 'ham-tien-bai-bien',
        'insights' => [
            ['slug' => 'cuoi-tuan-sai-gon', 'code' => 'sgn-weekend', 'vi' => 'Cuối tuần từ Sài Gòn', 'en' => 'Weekend from Saigon',
                'subtitle_vi' => 'Limo 4–5h — tour ngày & 2N1D resort.', 'subtitle_en' => '4–5h limo — day trips & 2N1D resort.',
                'seo_vi' => 'Intent cửa ngõ SGN — không trùng zone resort Ham Tien GEO.', 'seo_en' => 'Saigon gateway intent — not the Ham Tien resort GEO page.',
                'slugs' => ['sai-gon-mui-ne-2n1d-weekend', 'sai-gon-mui-ne-tour-ngay']],
            ['slug' => 'doi-cat-jeep', 'code' => 'sand-dunes', 'vi' => 'Đồi cát & jeep', 'en' => 'Sand dunes & jeep',
                'subtitle_vi' => 'Đỏ sunrise, trắng Bàu Trắng, Suối Tiên.', 'subtitle_en' => 'Red sunrise, White Bau Trang, Fairy Stream.',
                'seo_vi' => 'Trải nghiệm signature Mũi Né — lọc theo hoạt động, không theo zone đồi cát.', 'seo_en' => 'Signature Mui Ne experience — activity filter, not dune zone page.',
                'slugs' => ['tour-ngay-doi-cat-suoi-tien', 'jeep-doi-cat-do-sunrise', 'jeep-doi-cat-trang-bau-trang', 'tour-ngay-private-jeep-dunes']],
            ['slug' => 'kite-windsurf', 'code' => 'kite-surf', 'vi' => 'Kite-surf & windsurf', 'en' => 'Kite-surf & windsurf',
                'subtitle_vi' => 'Mùa gió Nov–Mar — lesson + resort.', 'subtitle_en' => 'Wind season Nov–Mar — lessons + resort.',
                'seo_vi' => 'Thiên đường kite Việt Nam — gói 3N2D tham khảo.', 'seo_en' => 'Vietnam kite capital — 3N2D packages.',
                'slugs' => ['mui-ne-3n2d-kite-surf-package', 'ham-tien-beach-kite-culture']],
            ['slug' => 'lang-chai-hai-san', 'code' => 'fishing-seafood', 'vi' => 'Làng chài & hải sản', 'en' => 'Fishing village & seafood',
                'subtitle_vi' => 'Sáng sớm thuyền về, food tour tối.', 'subtitle_en' => 'Morning boats, evening food tours.',
                'seo_vi' => 'Văn hoá biển Phan Thiết — nước mắm và làng chài.', 'seo_en' => 'Phan Thiet sea culture — fish sauce and fishing village.',
                'slugs' => ['lang-chai-mui-ne-sang', 'food-tour-phan-thiet-dem']],
            ['slug' => 'gia-dinh-resort', 'code' => 'family', 'vi' => 'Gia đình & resort', 'en' => 'Family & resort',
                'subtitle_vi' => 'Jeep chiều, hồ bơi — không 5h sáng.', 'subtitle_en' => 'Afternoon jeep, pool — no 5am rush.',
                'seo_vi' => 'Phân khúc SGN weekend gia đình.', 'seo_en' => 'SGN weekend family segment.',
                'slugs' => ['gia-dinh-mui-ne-2n1d', 'mui-ne-2n1d-resort-dunes']],
            ['slug' => 'trang-mat-bien', 'code' => 'honeymoon', 'vi' => 'Trăng mật & cặp đôi', 'en' => 'Honeymoon & couples',
                'subtitle_vi' => 'Resort 4–5*, sunset cruise.', 'subtitle_en' => '4–5* resort, sunset cruise.',
                'seo_vi' => 'Mini honeymoon biển nóng gần SGN.', 'seo_en' => 'Hot beach mini honeymoon near Saigon.',
                'slugs' => ['honeymoon-mui-ne-3n2d']],
        ],
        'slug_insights' => [
            'tour-ngay-doi-cat-suoi-tien' => ['sand-dunes'],
            'jeep-doi-cat-do-sunrise' => ['sand-dunes'],
            'jeep-doi-cat-trang-bau-trang' => ['sand-dunes'],
            'suoi-tien-nua-ngay' => ['sand-dunes'],
            'lang-chai-mui-ne-sang' => ['fishing-seafood'],
            'ham-tien-beach-kite-culture' => ['kite-surf'],
            'phan-thiet-po-sah-inu-city' => ['day-trip'],
            'ke-ga-ta-cu-ngay' => ['day-trip'],
            'mui-ne-2n1d-resort-dunes' => ['family', 'sand-dunes'],
            'mui-ne-3n2d-kite-surf-package' => ['kite-surf'],
            'sai-gon-mui-ne-2n1d-weekend' => ['sgn-weekend', 'family'],
            'sai-gon-mui-ne-tour-ngay' => ['sgn-weekend', 'sand-dunes'],
            'da-lat-mui-ne-3n2d' => ['3n2d'],
            'nha-trang-mui-ne-2n1d' => ['2n1d'],
            'gia-dinh-mui-ne-2n1d' => ['family'],
            'honeymoon-mui-ne-3n2d' => ['honeymoon'],
            'food-tour-phan-thiet-dem' => ['fishing-seafood'],
            'tour-ngay-private-jeep-dunes' => ['sand-dunes'],
        ],
    ],
];

// Continue with remaining profiles in second part...
require __DIR__.'/rebuild_tour_themes_data.php';
