<?php

/**
 * Dữ liệu dịch vụ ViTravel — merge vào project/seed_vitravel.php
 *
 * @return array<string, mixed>
 */
return [
    'service_clusters' => [
        ['code' => 'train', 'nav_label' => 'Tàu', 'label' => 'Vé tàu hỏa', 'icon' => 'train', 'hub_key' => 'trains_hub', 'sort' => 1],
        ['code' => 'flight', 'nav_label' => 'Máy bay', 'label' => 'Vé máy bay', 'icon' => 'plane', 'hub_key' => 'flights_hub', 'sort' => 2],
        ['code' => 'stay', 'nav_label' => 'Lưu trú', 'label' => 'Khách sạn & Resort', 'icon' => 'building', 'hub_key' => 'stays_hub', 'sort' => 3],
        ['code' => 'experience', 'nav_label' => 'Vui chơi', 'label' => 'Vé vui chơi & trải nghiệm', 'icon' => 'sparkles', 'hub_key' => 'experiences_hub', 'sort' => 4],
        ['code' => 'other', 'nav_label' => 'Dịch vụ', 'label' => 'Dịch vụ khác', 'icon' => 'briefcase', 'hub_key' => 'extras_hub', 'sort' => 5],
    ],

    'service_categories' => [
        // TRAIN
        ['cluster' => 'train', 'slug' => 'ha-noi-da-nang', 'name' => 'Hà Nội — Đà Nẵng', 'sort' => 1, 'intro' => 'Tuyến Bắc — Trung xuyên dốc Hải Vân, phù hợp kết hợp tour miền Trung.'],
        ['cluster' => 'train', 'slug' => 'ha-noi-sai-gon', 'name' => 'Hà Nội — Sài Gòn', 'sort' => 2, 'intro' => 'Tuyến xuyên Việt dài nhất, trải nghiệm đất nước hình chữ S trên đường ray.'],
        ['cluster' => 'train', 'slug' => 'da-nang-sai-gon', 'name' => 'Đà Nẵng — Sài Gòn', 'sort' => 3, 'intro' => 'Kết nối miền Trung và Nam, lý tưởng sau khi khám phá Hội An — Huế.'],
        // FLIGHT
        ['cluster' => 'flight', 'slug' => 'noi-dia', 'name' => 'Vé nội địa', 'sort' => 1, 'intro' => 'Bay nhanh giữa các thành phố lớn — tiết kiệm thời gian so với đường bộ.'],
        ['cluster' => 'flight', 'slug' => 'quoc-te-chau-a', 'name' => 'Quốc tế châu Á', 'sort' => 2, 'intro' => 'Gói vé máy bay kết hợp tour Việt Nam — Bangkok, Singapore, Tokyo và hơn thế.'],
        ['cluster' => 'flight', 'slug' => 'thue-may-bay-rieng', 'name' => 'Thuê máy bay riêng', 'sort' => 3, 'intro' => 'Charter jet & trực thăng cho doanh nghiệp, đoàn VIP và sự kiện đặc biệt.'],
        // STAY
        ['cluster' => 'stay', 'slug' => 'phu-quoc', 'name' => 'Phú Quốc', 'sort' => 1, 'intro' => 'Resort biển đảo ngọc — bãi cát trắng, sunset và ẩm thực hải sản.'],
        ['cluster' => 'stay', 'slug' => 'da-nang-hoi-an', 'name' => 'Đà Nẵng & Hội An', 'sort' => 2, 'intro' => 'Resort ven biển Mỹ Khê, Sơn Trà và boutique gần phố cổ.'],
        ['cluster' => 'stay', 'slug' => 'nha-trang', 'name' => 'Nha Trang & Cam Ranh', 'sort' => 3, 'intro' => 'Bãi biển nhiệt đới, Vinpearl và resort hạng sang vịnh Cam Ranh.'],
        ['cluster' => 'stay', 'slug' => 'ha-long-cat-ba', 'name' => 'Hạ Long & miền Bắc', 'sort' => 4, 'intro' => 'Resort vịnh di sản, Sapa và nghỉ dưỡng núi rừng Tây Bắc.'],
        // EXPERIENCE
        ['cluster' => 'experience', 'slug' => 'vinpearl', 'name' => 'Vinpearl & công viên', 'sort' => 1, 'intro' => 'Vé vào cửa, combo safari và trải nghiệm giải trí VinGroup.'],
        ['cluster' => 'experience', 'slug' => 'cap-treo', 'name' => 'Cáp treo & Sun World', 'sort' => 2, 'intro' => 'Fansipan, Bà Nà Hills, Hòn Thơm — ngắm toàn cảnh từ trên cao.'],
        ['cluster' => 'experience', 'slug' => 'du-luon', 'name' => 'Dù lượn & bay nhẹ', 'sort' => 3, 'intro' => 'Paragliding Đà Nẵng, Đà Lạt và trải nghiệm bay tandem an toàn.'],
        ['cluster' => 'experience', 'slug' => 'cano', 'name' => 'Kayak & làng chài', 'sort' => 4, 'intro' => 'Chèo kayak, thuyền nan và thăm làng chài vịnh Hạ Long, Nha Trang.'],
        ['cluster' => 'experience', 'slug' => 'the-thao-bien', 'name' => 'Thể thao biển', 'sort' => 5, 'intro' => 'Jet ski, parasailing, lặn biển và các hoạt động mặn nước.'],
        // OTHER
        ['cluster' => 'other', 'slug' => 'thue-xe', 'name' => 'Thuê xe', 'sort' => 1],
        ['cluster' => 'other', 'slug' => 'spa', 'name' => 'Spa & wellness', 'sort' => 2],
        ['cluster' => 'other', 'slug' => 'massage', 'name' => 'Massage & trị liệu', 'sort' => 3],
        ['cluster' => 'other', 'slug' => 'shipper', 'name' => 'Gửi hành lý', 'sort' => 4],
        ['cluster' => 'other', 'slug' => 'huong-dan-vien', 'name' => 'Hướng dẫn viên riêng', 'sort' => 5],
        ['cluster' => 'other', 'slug' => 'y-te', 'name' => 'Hỗ trợ y tế', 'sort' => 6],
        ['cluster' => 'other', 'slug' => 'khan-cap', 'name' => 'Hỗ trợ khẩn cấp 24/7', 'sort' => 7],
    ],

    'services' => [
        // ── TRAIN (4) ────────────────────────────────────────────────────────
        [
            'code' => 'train-se1-soft-han-dad',
            'cluster' => 'train',
            'category_slug' => 'ha-noi-da-nang',
            'country_slug' => 'viet-nam',
            'title' => 'Tàu SE1 — Hà Nội → Đà Nẵng (Ghế mềm điều hoà)',
            'slug' => 'tau-se1-ha-noi-da-nang-ghe-mem',
            'price_from' => 450000,
            'currency' => 'VND',
            'rating' => 4.6,
            'review_count' => 312,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Ga Hà Nội → Ga Đà Nẵng',
            'summary' => 'Chuyến tàu SE1 khởi hành buổi tối từ Hà Nội, đến Đà Nẵng sáng hôm sau — tiết kiệm một đêm khách sạn và ngắm cảnh dọc đường qua Huế, đèo Hải Vân.',
            'highlights' => [
                'Ghế mềm điều hoà toa 5–6, chỗ ngồi rộng rãi',
                'Xuất phát 19:30 ga Hà Nội, đến Đà Nẵng ~11:30 sáng hôm sau',
                'Phục vụ suất ăn nhẹ và nước uống trên tàu (tùy toa)',
                'Phù hợp du khách muốn tiết kiệm thời gian và chi phí so với bay',
                'ViTravel hỗ trợ đặt vé, giao tận tay hoặc e-ticket',
            ],
            'inclusions' => ['Vé ghế mềm điều hoà theo hành trình', 'Phí dịch vụ đặt vé ViTravel', 'Hướng dẫn lên tàu qua Zalo/email'],
            'exclusions' => ['Suất ăn chính (có thể đặt thêm trên tàu)', 'Đưa đón sân bay/ khách sạn', 'Bảo hiểm du lịch'],
            'notes' => ['Giá tham khảo theo mùa cao điểm Tết — vui lòng báo giá lại trước khi thanh toán.', 'Trẻ em dưới 4 tuổi miễn phí nếu ngồi cùng ba mẹ, không chiếm ghế.'],
            'attrs' => [
                'from' => 'Hà Nội',
                'to' => 'Đà Nẵng',
                'duration_hours' => 16,
                'operator' => 'Đường sắt Việt Nam',
                'train_class' => 'ghế mềm điều hoà',
                'train_number' => 'SE1',
            ],
            'options' => [
                ['code' => 'se1-soft-standard', 'name' => 'Ghế mềm toa 5', 'price_from' => 450000],
                ['code' => 'se1-soft-vip', 'name' => 'Ghế mềm toa 6 (VIP)', 'price_from' => 520000],
            ],
            'faqs' => [
                ['q' => 'Có thể đổi ngày sau khi mua vé không?', 'a' => 'Đổi ngày trước 12 giờ so với giờ tàu chạy, phí đổi theo quy định ĐSVN (thường 20–30% giá vé).'],
            ],
            'en' => [
                'title' => 'SE1 Train — Hanoi to Da Nang (Air-conditioned Soft Seat)',
                'summary' => 'Overnight SE1 service departing Hanoi in the evening, arriving Da Nang next morning — save a hotel night and enjoy the scenic route via Hue and Hai Van Pass.',
            ],
        ],
        [
            'code' => 'train-se1-sleeper-han-dad',
            'cluster' => 'train',
            'category_slug' => 'ha-noi-da-nang',
            'country_slug' => 'viet-nam',
            'title' => 'Tàu SE1 — Hà Nội → Đà Nẵng (Giường nằm 4–6 chỗ)',
            'slug' => 'tau-se1-ha-noi-da-nang-giuong-nam',
            'price_from' => 780000,
            'currency' => 'VND',
            'rating' => 4.7,
            'review_count' => 198,
            'is_featured' => true,
            'is_hot_deal' => true,
            'discount_badge' => 'Giường nằm',
            'location_label' => 'Ga Hà Nội → Ga Đà Nẵng',
            'summary' => 'Giường nằm kín điều hoà trên tàu SE1 — nghỉ ngơi thoải mái suốt hành trình xuyên đêm, phù hợp gia đình và cặp đôi.',
            'highlights' => [
                'Giường nằm 4 hoặc 6 chỗ, chăn ga gối sạch sẽ',
                'Toa kín có điều hoà, ổ cắm sạc điện thoại',
                'Hành trình qua Huế — đèo Hải Vân — Đà Nẵng',
                'Nhân viên tàu hỗ trợ suốt chuyến đi',
                'ViTravel ưu tiên giường dưới khi còn chỗ',
            ],
            'inclusions' => ['Vé giường nằm theo hành trình', 'Chăn ga gối trên tàu', 'Phí đặt vé ViTravel'],
            'exclusions' => ['Bữa ăn (đặt thêm trên tàu hoặc mang theo)', 'Đưa đón ga'],
            'notes' => ['Giường 4 chỗ đắt hơn giường 6 chỗ khoảng 150.000–200.000đ/vé.', 'Mang theo CMND/CCCD khi lên tàu.'],
            'attrs' => [
                'from' => 'Hà Nội',
                'to' => 'Đà Nẵng',
                'duration_hours' => 16,
                'operator' => 'Đường sắt Việt Nam',
                'train_class' => 'giường nằm kín điều hoà',
                'train_number' => 'SE1',
            ],
            'options' => [
                ['code' => 'se1-sleeper-6', 'name' => 'Giường nằm 6 chỗ', 'price_from' => 780000],
                ['code' => 'se1-sleeper-4', 'name' => 'Giường nằm 4 chỗ', 'price_from' => 950000],
            ],
        ],
        [
            'code' => 'train-se3-soft-han-sgn',
            'cluster' => 'train',
            'category_slug' => 'ha-noi-sai-gon',
            'country_slug' => 'viet-nam',
            'title' => 'Tàu SE3 — Hà Nội → Sài Gòn (Ghế mềm điều hoà)',
            'slug' => 'tau-se3-ha-noi-sai-gon-ghe-mem',
            'price_from' => 850000,
            'currency' => 'VND',
            'rating' => 4.5,
            'review_count' => 245,
            'is_featured' => false,
            'is_hot_deal' => false,
            'location_label' => 'Ga Hà Nội → Ga Sài Gòn',
            'summary' => 'Hành trình xuyên Việt ~30 giờ trên tàu SE3 — trải nghiệm đích thực đất nước hình chữ S, dừng chân tại các thành phố lớn dọc đường.',
            'highlights' => [
                'Tuyến dài nhất Việt Nam — trải nghiệm độc đáo cho du khách thích khám phá',
                'Ghế mềm điều hoà, có thể đi bộ trên boong tàu',
                'Đi qua Vinh, Huế, Đà Nẵng, Nha Trang trước khi đến Sài Gòn',
                'Giá vé hợp lý so với nhiều chặng bay nối chuyến',
                'ViTravel tư vấn lịch trình kết hợp dừng chân',
            ],
            'inclusions' => ['Vé ghế mềm SE3 toàn tuyến', 'Phí đặt vé'],
            'exclusions' => ['Suất ăn', 'Khách sạn nghỉ giữa chặng nếu xuống ga dừng'],
            'notes' => ['Có thể mua vé từng chặng (vd: Hà Nội — Huế) — liên hệ tư vấn.'],
            'attrs' => [
                'from' => 'Hà Nội',
                'to' => 'Sài Gòn',
                'duration_hours' => 30,
                'operator' => 'Đường sắt Việt Nam',
                'train_class' => 'ghế mềm điều hoà',
                'train_number' => 'SE3',
            ],
        ],
        [
            'code' => 'train-se3-sleeper-han-sgn',
            'cluster' => 'train',
            'category_slug' => 'ha-noi-sai-gon',
            'country_slug' => 'viet-nam',
            'title' => 'Tàu SE3/SE4 — Hà Nội ↔ Sài Gòn (Giường nằm)',
            'slug' => 'tau-se3-se4-ha-noi-sai-gon-giuong-nam',
            'price_from' => 1350000,
            'currency' => 'VND',
            'rating' => 4.6,
            'review_count' => 167,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Ga Hà Nội ↔ Ga Sài Gòn',
            'summary' => 'Giường nằm kín trên tuyến Bắc — Nam dài nhất — nghỉ ngơi trọn vẹn hai đêm trên tàu, lựa chọn của du khách muốn trải nghiệm đường sắt Việt Nam đầy đủ.',
            'highlights' => [
                'Giường nằm 4/6 chỗ, điều hoà suốt hành trình',
                'SE3 chiều Bắc → Nam, SE4 chiều Nam → Bắc',
                'Phù hợp backpacker và du khách thích di chuyển chậm',
                'Có thể kết hợp xuống ga Nha Trang, Đà Nẵng giữa đường',
                'ViTravel hỗ trợ đặt khứ hồi và vé từng chặng',
            ],
            'inclusions' => ['Vé giường nằm một chiều', 'Chăn ga gối', 'Phí dịch vụ đặt vé'],
            'exclusions' => ['Vé chiều về (đặt riêng)', 'Ăn uống trên tàu'],
            'notes' => ['Hành trình ~30–32 giờ tùy tàu và thời điểm trong năm.'],
            'attrs' => [
                'from' => 'Hà Nội',
                'to' => 'Sài Gòn',
                'duration_hours' => 31,
                'operator' => 'Đường sắt Việt Nam',
                'train_class' => 'giường nằm kín',
                'train_number' => 'SE3/SE4',
            ],
            'options' => [
                ['code' => 'se3-sleeper-6', 'name' => 'Giường 6 chỗ', 'price_from' => 1350000],
                ['code' => 'se3-sleeper-4', 'name' => 'Giường 4 chỗ', 'price_from' => 1580000],
            ],
        ],

        // ── FLIGHT (4) ───────────────────────────────────────────────────────
        [
            'code' => 'flight-sgn-han-economy',
            'cluster' => 'flight',
            'category_slug' => 'noi-dia',
            'country_slug' => 'viet-nam',
            'title' => 'Vé máy bay Sài Gòn — Hà Nội (Economy)',
            'slug' => 've-may-bay-sai-gon-ha-noi',
            'price_from' => 1290000,
            'currency' => 'VND',
            'rating' => 4.7,
            'review_count' => 892,
            'is_featured' => true,
            'is_hot_deal' => true,
            'discount_badge' => 'Bay thẳng',
            'location_label' => 'SGN Tân Sơn Nhất → HAN Nội Bài',
            'summary' => 'Chuyến bay nội địa phổ biến nhất Việt Nam — khoảng 2 giờ, nhiều chuyến/ngày từ Vietnam Airlines, Vietjet và Bamboo Airways. ViTravel báo giá tổng hợp, không phí ẩn.',
            'highlights' => [
                'Bay thẳng ~2 giờ 10 phút',
                'Nhiều khung giờ sáng — chiều — tối',
                'Hành lý ký gửi 7–20 kg tùy hãng',
                'Hỗ trợ đổi ngày theo điều kiện vé',
                'Giao e-ticket trong 30 phút sau thanh toán',
            ],
            'inclusions' => ['Vé máy bay một chiều (economy)', 'Thuế và phí sân bay', 'Phí dịch vụ ViTravel'],
            'exclusions' => ['Hành lý quá cân', 'Suất ăn trên máy bay (trừ hạng Business)', 'Đưa đón sân bay'],
            'notes' => ['Giá tham khảo — báo giá chính xác theo ngày bay khi đặt.', 'Lead-gen: ViTravel là đại lý, không phải hãng hàng không.'],
            'attrs' => [
                'from' => 'SGN',
                'to' => 'HAN',
                'airlines' => ['Vietnam Airlines', 'Vietjet Air', 'Bamboo Airways'],
                'flight_time' => '2h10m',
            ],
            'en' => ['title' => 'Ho Chi Minh City — Hanoi Flight (Economy)', 'summary' => 'Most popular domestic route in Vietnam — approx. 2 hours, multiple daily departures.'],
        ],
        [
            'code' => 'flight-han-dad-economy',
            'cluster' => 'flight',
            'category_slug' => 'noi-dia',
            'country_slug' => 'viet-nam',
            'title' => 'Vé máy bay Hà Nội — Đà Nẵng (Economy)',
            'slug' => 've-may-bay-ha-noi-da-nang',
            'price_from' => 990000,
            'currency' => 'VND',
            'rating' => 4.6,
            'review_count' => 654,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'HAN Nội Bài → DAD Đà Nẵng',
            'summary' => 'Bay nhanh miền Bắc — miền Trung trong 1 giờ 20 phút — lý tưởng kết hợp tour Hội An, Huế, Bà Nà Hills sau khi rời Hà Nội.',
            'highlights' => [
                'Thời gian bay ~1h20',
                '10+ chuyến/ngày mùa cao điểm',
                'Sân bay Đà Nẵng cách biển Mỹ Khê 15 phút',
                'Có thể kết hợp vé khứ hồi giá tốt',
                'Tư vấn nối chuyến tour miền Trung',
            ],
            'inclusions' => ['Vé một chiều economy', 'Thuế phí sân bay'],
            'exclusions' => ['Hành lý mua thêm', 'Chọn chỗ ngồi trả phí'],
            'notes' => ['Giá thấp nhất thường vào sáng sớm hoặc khuya.'],
            'attrs' => [
                'from' => 'HAN',
                'to' => 'DAD',
                'airlines' => ['Vietnam Airlines', 'Vietjet Air', 'Bamboo Airways'],
                'flight_time' => '1h20m',
            ],
        ],
        [
            'code' => 'flight-han-bkk-package',
            'cluster' => 'flight',
            'category_slug' => 'quoc-te-chau-a',
            'country_slug' => 'viet-nam',
            'title' => 'Gói vé Hà Nội — Bangkok + tour nối chuyến',
            'slug' => 'goi-ve-ha-noi-bangkok-tour',
            'price_from' => 3200000,
            'currency' => 'VND',
            'rating' => 4.8,
            'review_count' => 143,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'HAN → BKK (Suvarnabhumi)',
            'summary' => 'Gói lead-gen kết hợp vé quốc tế Hà Nội — Bangkok và tư vấn tour Thái Lan nối chuyến — phù hợp du khách Việt muốn mở rộng hành trình Đông Nam Á.',
            'highlights' => [
                'Bay thẳng ~2 giờ với Thai Airways, Vietjet hoặc Vietnam Airlines',
                'Tư vấn visa Thái Lan (miễn visa 30 ngày cho công dân VN)',
                'Combo tour Bangkok — Pattaya — Ayutthaya 3–5 ngày',
                'Hỗ trợ đặt khách sạn và đưa đón sân bay BKK',
                'Báo giá minh bạch, không cam kết giá cố định trên website',
            ],
            'inclusions' => ['Vé máy bay HAN–BKK (economy, tham khảo)', 'Tư vấn lịch trình Thái Lan', 'Phí dịch vụ đặt vé'],
            'exclusions' => ['Tour mặt đất Thái Lan (báo giá riêng)', 'Bảo hiểm du lịch quốc tế'],
            'notes' => ['Đây là gói tư vấn & đặt vé — giá thay đổi theo ngày bay và hãng.', 'Có thể thay BKK bằng SIN, KUL tùy nhu cầu.'],
            'attrs' => [
                'from' => 'HAN',
                'to' => 'BKK',
                'airlines' => ['Thai Airways', 'Vietjet Air', 'Vietnam Airlines'],
                'flight_time' => '2h00m',
            ],
            'faqs' => [
                ['q' => 'Công dân Việt có cần visa Thái Lan không?', 'a' => 'Hiện công dân Việt Nam được miễn visa nhập cảnh Thái Lan tối đa 30 ngày — vui lòng kiểm tra quy định mới nhất trước ngày bay.'],
            ],
        ],
        [
            'code' => 'flight-private-charter',
            'cluster' => 'flight',
            'category_slug' => 'thue-may-bay-rieng',
            'country_slug' => 'viet-nam',
            'title' => 'Thuê máy bay riêng & charter nội địa',
            'slug' => 'thue-may-bay-rieng-charter',
            'price_from' => 85000000,
            'currency' => 'VND',
            'rating' => 5.0,
            'review_count' => 28,
            'is_featured' => false,
            'is_hot_deal' => false,
            'location_label' => 'Toàn quốc — theo yêu cầu',
            'summary' => 'Dịch vụ charter jet và máy bay nhẹ cho doanh nghiệp, đoàn MICE, đám cưới destination và khách VIP — linh hoạt sân bay, giờ bay và lộ trình.',
            'highlights' => [
                'Máy bay phản lực nhẹ (Cessna Citation, Pilatus) hoặc trực thăng',
                'Bay thẳng các sân bay nội địa và một số sân bay khu vực',
                'Phục vụ riêng tư, tiết kiệm thời gian so với bay thương mại',
                'Phù hợp khảo sát dự án, FAM trip, sự kiện cao cấp',
                'ViTravel kết nối đối tác vận hành được cấp phép CAACV',
            ],
            'inclusions' => ['Tư vấn và báo giá charter', 'Sắp xếp slot sân bay', 'Hỗ trợ thủ tục hàng không'],
            'exclusions' => ['Chi phí bay thực tế (báo giá case-by-case)', 'Catering cao cấp', 'Ground handling nước ngoài'],
            'notes' => ['Giá from 85 triệu/chuyến ngắn — báo giá chi tiết sau khi nhận yêu cầu.', 'Đặt trước tối thiểu 7–14 ngày.'],
            'attrs' => [
                'from' => 'Theo yêu cầu',
                'to' => 'Theo yêu cầu',
                'airlines' => ['Đối tác charter Việt Nam'],
                'flight_time' => 'Linh hoạt',
            ],
            'en' => ['title' => 'Private Jet & Domestic Charter', 'summary' => 'Charter jets and light aircraft for corporate, MICE and VIP travel across Vietnam.'],
        ],

        // ── STAY (8) ─────────────────────────────────────────────────────────
        [
            'code' => 'stay-intercontinental-phu-quoc',
            'cluster' => 'stay',
            'category_slug' => 'phu-quoc',
            'country_slug' => 'viet-nam',
            'title' => 'InterContinental Phu Quoc Long Beach Resort',
            'slug' => 'intercontinental-phu-quoc-long-beach',
            'price_from' => 6500000,
            'currency' => 'VND',
            'rating' => 4.9,
            'review_count' => 421,
            'is_featured' => true,
            'is_hot_deal' => true,
            'discount_badge' => 'Resort 5★',
            'star_rating' => 5,
            'location_label' => 'Bãi Dài, Bắc đảo Phú Quốc',
            'summary' => 'Resort 5 sao dọc bãi biển dài nhất Phú Quốc — thiết kế hiện đại hướng biển, hồ bơi vô cực, spa I-Spa by ISLANDS và ẩm thực đa quốc gia. Lựa chọn hàng đầu cho kỳ nghỉ cao cấp trên đảo ngọc.',
            'highlights' => [
                'Mặt tiền bãi biển riêng dài hơn 1 km, cát trắng mịn',
                'Club InterContinental với lounge riêng và butler service',
                '4 nhà hàng & bar: Sora & Umi, LAVA, Sea Shack, Lobby Lounge',
                'Hồ bơi vô cực nhìn ra biển và hồ bơi trẻ em',
                'Spa I-Spa, phòng gym, kids club INK 360',
                'Gần sân bay Phú Quốc (~20 phút), thuận tiện kết hợp tour biển',
            ],
            'inclusions' => ['Phòng nghỉ theo loại đã chọn', 'Wi-Fi miễn phí', 'Phí dịch vụ đặt phòng ViTravel'],
            'exclusions' => ['Ăn sáng (tùy gói rate)', 'Minibar', 'Spa & hoạt động ngoài resort'],
            'notes' => ['Giá from/đêm tham khảo mùa thấp điểm — báo giá lại theo ngày check-in.', 'Trẻ em dưới 12 tuổi ngủ chung miễn phí (tùy chính sách phòng).'],
            'attrs' => [
                'amenities' => ['Hồ bơi vô cực', 'Spa', 'Bãi biển riêng', 'Kids club', 'Gym', 'Nhà hàng', 'Club lounge'],
                'check_in' => '15:00',
                'check_out' => '12:00',
                'property_type' => 'resort',
            ],
            'options' => [
                ['code' => 'ic-pq-deluxe', 'name' => 'Deluxe Ocean View', 'price_from' => 6500000, 'capacity' => 2, 'amenities' => ['Giường king', 'Ban công hướng biển', '55m²']],
                ['code' => 'ic-pq-suite', 'name' => 'One Bedroom Suite', 'price_from' => 9800000, 'capacity' => 3, 'amenities' => ['Phòng khách riêng', 'Bồn tắm', '85m²']],
                ['code' => 'ic-pq-villa', 'name' => 'Beachfront Villa', 'price_from' => 14500000, 'capacity' => 4, 'amenities' => ['Hồ bơi riêng', 'Sát bãi biển', 'Butler']],
            ],
            'en' => ['title' => 'InterContinental Phu Quoc Long Beach Resort', 'summary' => '5-star beachfront resort on Phu Quoc\'s longest beach — infinity pool, I-Spa and world-class dining.'],
        ],
        [
            'code' => 'stay-jw-marriott-phu-quoc',
            'cluster' => 'stay',
            'category_slug' => 'phu-quoc',
            'country_slug' => 'viet-nam',
            'title' => 'JW Marriott Phu Quoc Emerald Bay Resort & Spa',
            'slug' => 'jw-marriott-phu-quoc-emerald-bay',
            'price_from' => 7200000,
            'currency' => 'VND',
            'rating' => 4.9,
            'review_count' => 387,
            'is_featured' => true,
            'is_hot_deal' => false,
            'star_rating' => 5,
            'location_label' => 'Khem Beach, Nam đảo Phú Quốc',
            'summary' => 'Kiệt tác thiết kế bởi Bill Bensley — resort all-lakefront lấy cảm hứng từ trường đại học Pháp thuộc, mỗi phòng là một câu chuyện. Emerald Bay là biểu tượng luxury tại Phú Quốc.',
            'highlights' => [
                'Thiết kế Bill Bensley độc bản — không resort nào giống',
                'Bãi Khem trong vắt, ít đông đúc',
                'Chanterelle Spa by JW và hồ bơi hình con sên',
                'Nhà hàng Pink Pearl, Tempus Fugit, Red Rum',
                'Phòng ban công hướng hồ hoặc biển, nội thất cổ điển Á — Âu',
                'Phù hợp honeymoon và kỷ niệm đặc biệt',
            ],
            'inclusions' => ['Phòng nghỉ', 'Wi-Fi', 'Đưa đón sân bay (theo gói ưu đãi)'],
            'exclusions' => ['F&B ngoài gói', 'Tour ngoài resort'],
            'notes' => ['Resort adult-friendly, có khu vực gia đình.'],
            'attrs' => [
                'amenities' => ['Spa', 'Hồ bơi', 'Bãi biển', 'Fine dining', 'Art gallery', 'Gym'],
                'check_in' => '15:00',
                'check_out' => '12:00',
                'property_type' => 'resort',
            ],
            'options' => [
                ['code' => 'jw-pq-lagoon', 'name' => 'Lagoon View King', 'price_from' => 7200000, 'capacity' => 2],
                ['code' => 'jw-pq-ocean', 'name' => 'Ocean View King', 'price_from' => 8900000, 'capacity' => 2],
                ['code' => 'jw-pq-suite', 'name' => 'JW Suite', 'price_from' => 12800000, 'capacity' => 3],
            ],
        ],
        [
            'code' => 'stay-vinpearl-ha-long',
            'cluster' => 'stay',
            'category_slug' => 'ha-long-cat-ba',
            'country_slug' => 'viet-nam',
            'title' => 'Vinpearl Resort & Spa Hạ Long',
            'slug' => 'vinpearl-resort-spa-ha-long',
            'price_from' => 3800000,
            'currency' => 'VND',
            'rating' => 4.7,
            'review_count' => 512,
            'is_featured' => true,
            'is_hot_deal' => true,
            'discount_badge' => 'View vịnh',
            'star_rating' => 5,
            'location_label' => 'Đảo Rều, Vịnh Hạ Long, Quảng Ninh',
            'summary' => 'Resort trên đảo riêng giữa vịnh Hạ Long — view núi đá vôi, cáp treo nối đất liền, công viên nước Vinpearl Land và spa — kết hợp hoàn hảo nghỉ dưỡng & khám phá di sản.',
            'highlights' => [
                'View trực diện vịnh Hạ Long UNESCO',
                'Cáp treo Vinpearl nối Bãi Cháy — đảo Rều',
                'Vinpearl Land, sân golf, bể bơi ngoài trời lớn',
                'Spa Vincharm, nhà hàng hải sản và buffet quốc tế',
                'Thuận tiện kết hợp tour du thuyền 1–2 ngày',
                'Gia đình có trẻ nhỏ — nhiều hoạt động trong resort',
            ],
            'inclusions' => ['Phòng nghỉ', 'Wi-Fi', 'Khu vui chơi cơ bản (tùy gói)'],
            'exclusions' => ['Vinpearl Land vé lẻ', 'Tour du thuyền vịnh'],
            'notes' => ['Mùa đông có thể sương mù — view vịnh vẫn đẹp nhưng tắm biển hạn chế.'],
            'attrs' => [
                'amenities' => ['Spa', 'Hồ bơi', 'Công viên nước', 'Golf', 'Nhà hàng', 'Cáp treo'],
                'check_in' => '14:00',
                'check_out' => '12:00',
                'property_type' => 'resort',
            ],
            'options' => [
                ['code' => 'vp-hl-deluxe', 'name' => 'Deluxe Bay View', 'price_from' => 3800000, 'capacity' => 2],
                ['code' => 'vp-hl-suite', 'name' => 'Executive Suite', 'price_from' => 5500000, 'capacity' => 3],
            ],
        ],
        [
            'code' => 'stay-premier-village-phu-quoc',
            'cluster' => 'stay',
            'category_slug' => 'phu-quoc',
            'country_slug' => 'viet-nam',
            'title' => 'Premier Village Phu Quoc Resort',
            'slug' => 'premier-village-phu-quoc-resort',
            'price_from' => 5800000,
            'currency' => 'VND',
            'rating' => 4.8,
            'review_count' => 276,
            'is_featured' => false,
            'is_hot_deal' => false,
            'star_rating' => 5,
            'location_label' => 'Mũi Ông Đội, Nam Phú Quốc',
            'summary' => 'Toàn bộ là villa riêng biệt — mỗi căn có hồ bơi riêng, sân vườn và view biển. Managed by Accor, Premier Village là lựa chọn villa resort hàng đầu Phú Quốc cho nhóm bạn và gia đình.',
            'highlights' => [
                '100% villa — không có phòng khách sạn',
                'Hồ bơi riêng từng villa, bếp mini đầy đủ',
                'Bãi biển riêng Mũi Ông Đội — yên tĩnh',
                'The Market restaurant & Plumeria Spa',
                'Gần Sunset Sanato và các quán hải sản địa phương',
                'Phù hợp nhóm 4–8 người thuê villa 3 phòng ngủ',
            ],
            'inclusions' => ['Villa theo loại', 'Wi-Fi', 'Bãi biển riêng'],
            'exclusions' => ['Ăn sáng (có thể mua thêm)', 'BBQ setup'],
            'notes' => ['Villa 3BR phù hợp 6–8 khách — báo giá theo số người.'],
            'attrs' => [
                'amenities' => ['Hồ bơi riêng', 'Bếp mini', 'Spa', 'Bãi biển', 'Gym', 'Kids area'],
                'check_in' => '15:00',
                'check_out' => '12:00',
                'property_type' => 'villa resort',
            ],
            'options' => [
                ['code' => 'pv-pq-2br', 'name' => '2 Bedroom Pool Villa', 'price_from' => 5800000, 'capacity' => 4],
                ['code' => 'pv-pq-3br', 'name' => '3 Bedroom Pool Villa', 'price_from' => 8200000, 'capacity' => 6],
                ['code' => 'pv-pq-4br', 'name' => '4 Bedroom Beach Villa', 'price_from' => 11500000, 'capacity' => 8],
            ],
        ],
        [
            'code' => 'stay-furama-resort-danang',
            'cluster' => 'stay',
            'category_slug' => 'da-nang-hoi-an',
            'country_slug' => 'viet-nam',
            'title' => 'Furama Resort Danang',
            'slug' => 'furama-resort-danang',
            'price_from' => 4200000,
            'currency' => 'VND',
            'rating' => 4.8,
            'review_count' => 698,
            'is_featured' => true,
            'is_hot_deal' => false,
            'star_rating' => 5,
            'location_label' => '105 Võ Nguyên Giáp, Mỹ Khê, Đà Nẵng',
            'summary' => 'Resort biển kinh điển Đà Nẵng từ 1990s — bãi Mỹ Khê được Forbes bình chọn, laguna hồ bơi, Furama Villas và ẩm thực Việt — Nhật — Âu. Chuẩn mực nghỉ dưỡng miền Trung.',
            'highlights' => [
                'Bãi biển Mỹ Khê — top beach châu Á',
                'Lagoon pool 2.000 m² và Furama Villas riêng biệt',
                'Spa Fusion Maia, cooking class ẩm thực Việt',
                '5 nhà hàng: Café Indochine, Don Cipriani\'s, Tàya House…',
                '15 phút sân bay, 20 phút Hội An',
                'Tổ chức tiệc cưới beachfront uy tín',
            ],
            'inclusions' => ['Phòng/villa', 'Wi-Fi', 'Bãi biển & hồ bơi'],
            'exclusions' => ['Ăn sáng (trừ gói B&B)', 'Đưa đón'],
            'notes' => ['Có wing Furama Villas tách biệt — yên tĩnh hơn main building.'],
            'attrs' => [
                'amenities' => ['Lagoon pool', 'Spa', 'Bãi biển', 'Nhà hàng', 'Gym', 'Tennis'],
                'check_in' => '14:00',
                'check_out' => '12:00',
                'property_type' => 'resort',
            ],
            'options' => [
                ['code' => 'furama-garden', 'name' => 'Garden Superior', 'price_from' => 4200000, 'capacity' => 2],
                ['code' => 'furama-ocean', 'name' => 'Ocean Deluxe', 'price_from' => 5100000, 'capacity' => 2],
                ['code' => 'furama-villa', 'name' => 'Furama Villa 1BR', 'price_from' => 7800000, 'capacity' => 3],
            ],
        ],
        [
            'code' => 'stay-six-senses-ninh-van-bay',
            'cluster' => 'stay',
            'category_slug' => 'nha-trang',
            'country_slug' => 'viet-nam',
            'title' => 'Six Senses Ninh Van Bay',
            'slug' => 'six-senses-ninh-van-bay',
            'price_from' => 12500000,
            'currency' => 'VND',
            'rating' => 5.0,
            'review_count' => 189,
            'is_featured' => true,
            'is_hot_deal' => false,
            'star_rating' => 5,
            'location_label' => 'Vịnh Ninh Vân, Cam Ranh (đón từ Nha Trang)',
            'summary' => 'Resort chỉ đi bằng thuyền — villa trên đồi và sát biển, triết lý sustainable luxury của Six Senses. Trải nghiệm nghỉ dưỡng biểt lập đẳng cấp nhất miền Trung Việt Nam.',
            'highlights' => [
                'Boat-only access — cảm giác riêng tư tuyệt đối',
                'Villa hồ bơi riêng — Hill Top, Beach Front, Water Pool',
                'Six Senses Spa với liệu pháp holistic',
                'Dining by Design — ăn tối riêng trên bãi biển',
                'Organic garden, sustainability tour',
                'Phù hợp honeymoon ultra-luxury',
            ],
            'inclusions' => ['Villa', 'Boat transfer từ Nha Trang', 'Wi-Fi'],
            'exclusions' => ['F&B', 'Spa treatments', 'Bay transfer ngoài giờ'],
            'notes' => ['Resort không phù hợp trẻ em dưới 12 tuổi một số mùa — kiểm tra policy.'],
            'attrs' => [
                'amenities' => ['Private pool villa', 'Spa', 'Private beach', 'Organic garden', 'Yoga'],
                'check_in' => '14:00',
                'check_out' => '12:00',
                'property_type' => 'luxury villa resort',
            ],
            'options' => [
                ['code' => '6s-hill-villa', 'name' => 'Hill Top Pool Villa', 'price_from' => 12500000, 'capacity' => 2],
                ['code' => '6s-beach-villa', 'name' => 'Beach Front Pool Villa', 'price_from' => 15800000, 'capacity' => 2],
                ['code' => '6s-water-villa', 'name' => 'Water Pool Villa', 'price_from' => 18200000, 'capacity' => 2],
            ],
            'en' => ['title' => 'Six Senses Ninh Van Bay', 'summary' => 'Boat-access only luxury resort — private pool villas and sustainable wellness in Ninh Van Bay.'],
        ],
        [
            'code' => 'stay-hotel-de-la-coupole-sapa',
            'cluster' => 'stay',
            'category_slug' => 'ha-long-cat-ba',
            'country_slug' => 'viet-nam',
            'title' => 'Hotel de la Coupole — MGallery Sapa',
            'slug' => 'hotel-de-la-coupole-mgallery-sapa',
            'price_from' => 4800000,
            'currency' => 'VND',
            'rating' => 4.8,
            'review_count' => 334,
            'is_featured' => true,
            'is_hot_deal' => false,
            'star_rating' => 5,
            'location_label' => '01 Hoàng Liên, Sa Pa, Lào Cai',
            'summary' => 'Khách sạn biểu tượng Sa Pa — thiết kế lấy cảm hứng Haute Couture Pháp gặp văn hoá vùng cao Tây Bắc. View ruộng bậc thang và Fansipan, indoor pool kính trong suốt nổi tiếng trên mạng xã hội.',
            'highlights' => [
                'Thiết kế độc đáo — dome, màu sắc và nội thất couture',
                'Indoor pool view núi Hoàng Liên Sơn',
                'Nhà hàng Chic, Absinthe Bar',
                'Spa Hmong heritage treatments',
                'Gần ga cáp treo Fansipan và bản Cát Cát',
                'Ấm áp mùa đông — lò sưởi và không khí alpine',
            ],
            'inclusions' => ['Phòng nghỉ', 'Wi-Fi', 'Indoor pool'],
            'exclusions' => ['Ăn sáng', 'Cáp treo Fansipan', 'Tour trekking'],
            'notes' => ['Sa Pa mùa đông có thể dưới 10°C — mang áo ấm.', 'Book sớm dịp lễ 30/4 và lễ hội mùa xuân.'],
            'attrs' => [
                'amenities' => ['Indoor pool', 'Spa', 'Nhà hàng', 'Bar', 'Gym', 'View núi'],
                'check_in' => '15:00',
                'check_out' => '12:00',
                'property_type' => 'boutique hotel',
            ],
            'options' => [
                ['code' => 'coupole-classic', 'name' => 'Classic Room', 'price_from' => 4800000, 'capacity' => 2],
                ['code' => 'coupole-valley', 'name' => 'Valley View', 'price_from' => 6200000, 'capacity' => 2],
                ['code' => 'coupole-suite', 'name' => 'Couture Suite', 'price_from' => 8900000, 'capacity' => 3],
            ],
        ],
        [
            'code' => 'stay-azerai-ke-ga-bay',
            'cluster' => 'stay',
            'category_slug' => 'nha-trang',
            'country_slug' => 'viet-nam',
            'title' => 'Azerai Ke Ga Bay',
            'slug' => 'azerai-ke-ga-bay',
            'price_from' => 8500000,
            'currency' => 'VND',
            'rating' => 4.9,
            'review_count' => 156,
            'is_featured' => false,
            'is_hot_deal' => true,
            'discount_badge' => 'Boutique',
            'star_rating' => 5,
            'location_label' => 'Bình Thuận — bán đảo Ke Ga, cách Phan Thiết 30 km',
            'summary' => 'Resort boutique 32 villa của Adrian Zecha (Aman founder) — bán đảo hoang sơ Ke Ga, hải đăng cổ, bãi biển riêng và spa tĩnh lặng. Trải nghiệm nghỉ dưỡng tinh tế, xa đám đông Nha Trang.',
            'highlights' => [
                'Chỉ 32 villa — không đông, không ồn',
                'Hải đăng Ke Ga — biểu tượng Bình Thuận',
                'Spa trong villa hoặc pavilion riêng',
                'Nhà hàng The Dining Room — seafood & Vietnamese',
                'Hoạt động: kayak, biking, tour hải đăng',
                'Kết hợp tốt với Mũi Né sand dunes',
            ],
            'inclusions' => ['Villa', 'Wi-Fi', 'Bãi biển riêng', 'Xe đạp'],
            'exclusions' => ['F&B', 'Spa', 'Transfer từ sân bay (có thu phí)'],
            'notes' => ['Resort cách Nha Trang ~2.5 giờ — phù hợp nghỉ cuối/chặng riêng.'],
            'attrs' => [
                'amenities' => ['Private beach', 'Spa', 'Restaurant', 'Kayak', 'Bicycle', 'Lighthouse tour'],
                'check_in' => '14:00',
                'check_out' => '12:00',
                'property_type' => 'boutique resort',
            ],
            'options' => [
                ['code' => 'azerai-garden-villa', 'name' => 'Garden Villa', 'price_from' => 8500000, 'capacity' => 2],
                ['code' => 'azerai-ocean-villa', 'name' => 'Ocean Villa', 'price_from' => 10200000, 'capacity' => 2],
                ['code' => 'azerai-pool-villa', 'name' => 'Pool Villa', 'price_from' => 11800000, 'capacity' => 3],
            ],
        ],

        // ── EXPERIENCE (9) ───────────────────────────────────────────────────
        [
            'code' => 'exp-vinpearl-land-nha-trang',
            'cluster' => 'experience',
            'category_slug' => 'vinpearl',
            'country_slug' => 'viet-nam',
            'title' => 'Vé Vinpearl Land Nha Trang (cáp treo + công viên)',
            'slug' => 've-vinpearl-land-nha-trang',
            'price_from' => 950000,
            'currency' => 'VND',
            'rating' => 4.7,
            'review_count' => 1243,
            'is_featured' => true,
            'is_hot_deal' => true,
            'discount_badge' => 'Combo',
            'location_label' => 'Đảo Hòn Tre, Nha Trang',
            'summary' => 'Vé combo cáp treo vượt biển dài nhất Việt Nam và vào cửa Vinpearl Land — tàu lượn, công viên nước, show nhạc nước và thủy cung.',
            'highlights' => [
                'Cáp treo 3.320m — kỷ lục Việt Nam',
                'Tàu lượn, công viên nước, khu trò chơi trong nhà',
                'Show nhạc nước buổi tối (theo lịch)',
                'Thủy cung và khu vui chơi trẻ em',
                'ViTravel giao vé QR, không xếp hàng mua tại quầy',
            ],
            'inclusions' => ['Vé cáp treo khứ hồi', 'Vé vào Vinpearl Land', 'Phí dịch vụ'],
            'exclusions' => ['Ăn uống trong công viên', 'Trò chơi tính phí riêng', 'Đưa đón khách sạn'],
            'notes' => ['Trẻ em cao dưới 1m miễn phí (theo quy định Vinpearl).'],
            'attrs' => ['duration_hours' => 6, 'venue' => 'Vinpearl Land Nha Trang', 'ticket_type' => 'combo'],
        ],
        [
            'code' => 'exp-vinpearl-safari-phu-quoc',
            'cluster' => 'experience',
            'category_slug' => 'vinpearl',
            'country_slug' => 'viet-nam',
            'title' => 'Vinpearl Safari Phú Quốc — vé vào cửa',
            'slug' => 'vinpearl-safari-phu-quoc',
            'price_from' => 650000,
            'currency' => 'VND',
            'rating' => 4.6,
            'review_count' => 876,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Bãi Dài, Phú Quốc',
            'summary' => 'Safari bán hoang dã lớn nhất Việt Nam — xe bus mui trần qua chuồng thú mở, nhà hơi, show chim và khu trưng bày ban ngày.',
            'highlights' => [
                '300+ loài, 3.000 cá thể động vật',
                'Safari bus mui trần — hươu cao cổ ăn từ tay',
                'Show chim và show hải cẩn (theo lịch)',
                'Khu Giraffe Restaurant view bầy hươu cao cổ',
                'Phù hợp gia đình có trẻ em',
            ],
            'inclusions' => ['Vé vào cửa', 'Safari bus', 'Phí dịch vụ ViTravel'],
            'exclusions' => ['Ăn uống', 'Đưa đón', 'Gói combo VinWonders'],
            'notes' => ['Nên đi sáng sớm — thú hoạt động mạnh hơn buổi trưa.'],
            'attrs' => ['duration_hours' => 4, 'venue' => 'Vinpearl Safari Phú Quốc', 'ticket_type' => 'admission'],
        ],
        [
            'code' => 'exp-fansipan-cable-car',
            'cluster' => 'experience',
            'category_slug' => 'cap-treo',
            'country_slug' => 'viet-nam',
            'title' => 'Cáp treo Fansipan Legend — Sun World Fansipan',
            'slug' => 'cap-treo-fansipan-legend',
            'price_from' => 750000,
            'currency' => 'VND',
            'rating' => 4.8,
            'review_count' => 2105,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Sa Pa, Lào Cai — đỉnh Fansipan 3.143m',
            'summary' => 'Chinh phục nóc nhà Đông Dương bằng cáp treo 3 cáp nối tiếp — không cần leo 2–3 ngày, view ruộng bậc thang và đỉnh núi phủ sương.',
            'highlights' => [
                'Độ cao 3.143m — cao nhất Đông Nam Á',
                'Cáp treo 3 cáp, giữ kỷ lục Guinness',
                'Chùa và tượng Phật trên đỉnh',
                'View Hoàng Liên Sơn 360°',
                'Kết hợp tốt với lưu trú Hotel de la Coupole',
            ],
            'inclusions' => ['Vé cáp treo khứ hồi', 'Phí dịch vụ'],
            'exclusions' => ['Ăn uống trên đỉnh', 'Đưa đón Sa Pa', 'Quần áo ấm (mùa đông)'],
            'notes' => ['Nhiệt độ đỉnh có thể 5–10°C — mang áo khoác.', 'Sương mù che view — may rủi theo thời tiết.'],
            'attrs' => ['duration_hours' => 3, 'venue' => 'Sun World Fansipan Legend', 'peak_elevation' => '3143m'],
        ],
        [
            'code' => 'exp-sunworld-ba-na-hills',
            'cluster' => 'experience',
            'category_slug' => 'cap-treo',
            'country_slug' => 'viet-nam',
            'title' => 'Sun World Ba Na Hills — vé cáp treo & công viên',
            'slug' => 'sunworld-ba-na-hills',
            'price_from' => 900000,
            'currency' => 'VND',
            'rating' => 4.7,
            'review_count' => 3421,
            'is_featured' => true,
            'is_hot_deal' => true,
            'discount_badge' => 'Hot',
            'location_label' => 'Bà Nà Hills, Đà Nẵng',
            'summary' => 'Làng Pháp trên mây, Cầu Vàng Golden Bridge, cáp treo dài và vui chơi giải trí — điểm đến số 1 Đà Nẵng cho mọi lứa tuổi.',
            'highlights' => [
                'Cầu Vàng — biểu tượng du lịch Việt Nam',
                'Làng Pháp cổ điển, nhà thờ, quảng trường',
                'Cáp treo 4 cáp — kỷ lục dài',
                'Fantasy Park — trò chơi trong nhà',
                'Buffet trưa optional tại nhà hàng Morin',
            ],
            'inclusions' => ['Vé cáp treo khứ hồi', 'Vé vào cổng', 'Phí dịch vụ'],
            'exclusions' => ['Buffet trưa', 'Đưa đón', 'Trò chơi tính phí'],
            'notes' => ['Nên đi sớm 7–8h tránh đông.', 'Mùa mưa sương mù — view hạn chế.'],
            'attrs' => ['duration_hours' => 5, 'venue' => 'Sun World Ba Na Hills'],
        ],
        [
            'code' => 'exp-hon-thom-cable-car',
            'cluster' => 'experience',
            'category_slug' => 'cap-treo',
            'country_slug' => 'viet-nam',
            'title' => 'Cáp treo Hòn Thơm — Sun World Hon Thom',
            'slug' => 'cap-treo-hon-thom-phu-quoc',
            'price_from' => 600000,
            'currency' => 'VND',
            'rating' => 4.6,
            'review_count' => 987,
            'is_featured' => false,
            'is_hot_deal' => false,
            'location_label' => 'Nam Phú Quốc — An Thới',
            'summary' => 'Cáp treo vượt biển 7.899m nối An Thới — đảo Hòn Thơm, kết hợp bãi biển hoang sơ và công viên nước Aquatopia.',
            'highlights' => [
                'Cáp treo biển dài nhất thế giới (theo Sun Group)',
                'Bãi biển Kem và bãi Sao gần đó',
                'Aquatopia water park trên Hòn Thơm',
                'View toàn cảnh quần đảo An Thới',
                'Combo vé cáp treo + công viên nước tiết kiệm',
            ],
            'inclusions' => ['Vé cáp treo khứ hồi', 'Phí dịch vụ'],
            'exclusions' => ['Aquatopia (mua combo riêng)', 'Ăn uống', 'Đưa đón'],
            'notes' => ['Thời tiết xấu có thể tạm dừng cáp treo — hoàn vé theo quy định.'],
            'attrs' => ['duration_hours' => 4, 'venue' => 'Sun World Hon Thom Nature Park'],
        ],
        [
            'code' => 'exp-paragliding-da-nang',
            'cluster' => 'experience',
            'category_slug' => 'du-luon',
            'country_slug' => 'viet-nam',
            'title' => 'Dù lượn tandem Đà Nẵng — Son Tra / Hòa Nhơn',
            'slug' => 'du-luon-tandem-da-nang',
            'price_from' => 1800000,
            'currency' => 'VND',
            'rating' => 4.9,
            'review_count' => 412,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Sơn Trà / Hòa Nhơn, Đà Nẵng',
            'summary' => 'Bay tandem cùng phi công chứng nhận — lượn trên bán đảo Sơn Trà hoặc đồi Hòa Nhơn, nhìn toàn cảnh biển Mỹ Khê, cầu Rồng và đèo Hải Vân.',
            'highlights' => [
                'Phi công tandem kinh nghiệm 500+ chuyến',
                'Thời gian bay 15–20 phút tùy gió',
                'GoPro video optional (phí riêng)',
                'Briefing an toàn trước chuyến bay',
                'Khung giờ sáng sớm — gió ổn định nhất',
            ],
            'inclusions' => ['1 chuyến bay tandem', 'Thiết bị bảo hộ', 'Phi công', 'Phí dịch vụ'],
            'exclusions' => ['Video/photo GoPro', 'Đưa đón', 'Bảo hiểm mua thêm'],
            'notes' => ['Phụ thuộc thời tiết — có thể hoãn sang ngày khác.', 'Cân nặng 40–90 kg.'],
            'attrs' => ['duration_hours' => 2, 'activity' => 'paragliding', 'location' => 'Da Nang'],
        ],
        [
            'code' => 'exp-kayak-halong-floating-village',
            'cluster' => 'experience',
            'category_slug' => 'cano',
            'country_slug' => 'viet-nam',
            'title' => 'Kayak & làng chài Vung Viêng — Vịnh Hạ Long',
            'slug' => 'kayak-lang-chai-vung-vieng-ha-long',
            'price_from' => 450000,
            'currency' => 'VND',
            'rating' => 4.7,
            'review_count' => 567,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Vùng vịnh Hạ Long — làng chài Vung Viêng',
            'summary' => 'Chèo kayak qua hang động và vùng nước yên tĩnh, ghé làng chài nổi Vung Viêng — trải nghiệm đích thực cuộc sống trên vịnh.',
            'highlights' => [
                'Kayak 2 người qua hang và vùng nước trong xanh',
                'Thăm làng chài — xem nuôi cá bè',
                'Hướng dẫn viên địa phương',
                'Thường kết hợp tour day boat hoặc du thuyền',
                'Áo phao và thiết bị an toàn đầy đủ',
            ],
            'inclusions' => ['Kayak & thiết bị', 'HDV', 'Phí làng chài'],
            'exclusions' => ['Tour tàu/du thuyền (book riêng hoặc combo)', 'Ăn trưa'],
            'notes' => ['Hoạt động ngoài trời — mặc đồ nhanh khô.', 'Có thể book combo day cruise + kayak.'],
            'attrs' => ['duration_hours' => 3, 'activity' => 'kayak', 'location' => 'Ha Long Bay'],
        ],
        [
            'code' => 'exp-jet-ski-nha-trang',
            'cluster' => 'experience',
            'category_slug' => 'the-thao-bien',
            'country_slug' => 'viet-nam',
            'title' => 'Jet ski Nha Trang — Bãi Trí Nguyên',
            'slug' => 'jet-ski-nha-trang',
            'price_from' => 800000,
            'currency' => 'VND',
            'rating' => 4.5,
            'review_count' => 334,
            'is_featured' => false,
            'is_hot_deal' => true,
            'discount_badge' => '15 phút',
            'location_label' => 'Bãi Trí Nguyên, Nha Trang',
            'summary' => 'Lái jet ski trên vịnh Nha Trang — 15 phút adrenaline với hướng dẫn cơ bản, view cầu Trần Phú và đảo xa bờ.',
            'highlights' => [
                'Jet ski Yamaha — bảo dưỡng định kỳ',
                '15 phút lái (có thể gia hạn)',
                'Áo phao và briefing an toàn',
                'Không cần bằng lái (theo khu vực có giám sát)',
                'Chụp ảnh action optional',
            ],
            'inclusions' => ['15 phút jet ski', 'Áo phao', 'Briefing'],
            'exclusions' => ['Gia hạn thêm phút', 'Photo package', 'Đưa đón'],
            'notes' => ['Trẻ em dưới 16 tuổi ngồi sau người lớn.'],
            'attrs' => ['duration_hours' => 1, 'activity' => 'jet_ski', 'location' => 'Nha Trang'],
            'options' => [
                ['code' => 'jetski-15', 'name' => '15 phút', 'price_from' => 800000],
                ['code' => 'jetski-30', 'name' => '30 phút', 'price_from' => 1400000],
            ],
        ],
        [
            'code' => 'exp-parasailing-phu-quoc',
            'cluster' => 'experience',
            'category_slug' => 'the-thao-bien',
            'country_slug' => 'viet-nam',
            'title' => 'Parasailing Phú Quốc — Bãi Sao / Long Beach',
            'slug' => 'parasailing-phu-quoc',
            'price_from' => 650000,
            'currency' => 'VND',
            'rating' => 4.6,
            'review_count' => 289,
            'is_featured' => false,
            'is_hot_deal' => false,
            'location_label' => 'Bãi Sao / Bãi Dài, Phú Quốc',
            'summary' => 'Bay parasail cao 80–100m phía trên biển Phú Quốc — view toàn cảnh bãi cát trắng và rừng nhiệt đới, 8–10 phút trên không.',
            'highlights' => [
                'Bay đôi hoặc đơn — tùy cân nặng',
                'Tàu kéo an toàn, thiết bị kiểm định',
                'View bãi Sao từ trên cao',
                'Không cần kinh nghiệm — ngồi harness',
                'Hoạt động buổi sáng — gió và sóng ổn',
            ],
            'inclusions' => ['1 lần parasail (~8 phút)', 'Thiết bị an toàn', 'Phí dịch vụ'],
            'exclusions' => ['Photo/video trên không', 'Đưa đón'],
            'notes' => ['Hủy nếu thời tiết xấu — hoàn 100%.'],
            'attrs' => ['duration_hours' => 1, 'activity' => 'parasailing', 'location' => 'Phu Quoc'],
        ],

        // ── OTHER (7) ────────────────────────────────────────────────────────
        [
            'code' => 'other-car-rental',
            'cluster' => 'other',
            'category_slug' => 'thue-xe',
            'country_slug' => 'viet-nam',
            'title' => 'Thuê xe — tự lái & có lái',
            'slug' => 'thue-xe-tu-lai-co-lai',
            'price_from' => 850000,
            'currency' => 'VND',
            'rating' => 4.7,
            'review_count' => 1123,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Hà Nội, Đà Nẵng, Sài Gòn, Phú Quốc — toàn quốc',
            'summary' => 'Thuê xe tự lái sedan/SUV hoặc xe có tài xế theo ngày — giao tận khách sạn, phù hợp city tour, intercity và lịch trình tour tùy chỉnh.',
            'highlights' => [
                'Tự lái: Toyota Vios, Fortuner — xe mới dưới 3 năm',
                'Có lái: tài xế kinh nghiệm, tiếng Anh cơ bản (yêu cầu trước)',
                'Giao — nhận xe tại khách sạn hoặc sân bay',
                'Bảo hiểm vật chất cơ bản (tự lái) / xăng + lương tài xế (có lái)',
                'Hỗ trợ 24/7 khi sự cố trên đường',
            ],
            'inclusions' => ['Xe theo gói đã chọn', 'Bảo hiểm/phí cơ bản theo loại', 'Phí dịch vụ ViTravel'],
            'exclusions' => ['Xăng dầu (tự lái)', 'Tip tài xế', 'Overtime', 'Phí giao xe ngoài nội thành'],
            'notes' => ['Tự lái cần GPLX Việt Nam hoặc IDP.', 'Intercity có lái — báo giá theo chuyến.'],
            'attrs' => ['service_type' => 'car_rental', 'rental_modes' => ['self_drive', 'with_driver']],
            'options' => [
                ['code' => 'rent-vios-self', 'name' => 'Vios tự lái (4 chỗ/ngày)', 'price_from' => 850000, 'description' => 'Giới hạn 200 km/ngày'],
                ['code' => 'rent-fortuner-self', 'name' => 'Fortuner tự lái (7 chỗ/ngày)', 'price_from' => 1350000],
                ['code' => 'rent-with-driver', 'name' => 'Xe có lái (8–10 giờ/ngày)', 'price_from' => 1200000, 'description' => 'Sedan 4–7 chỗ, xăng trong giới hạn km'],
            ],
        ],
        [
            'code' => 'other-spa-wellness',
            'cluster' => 'other',
            'category_slug' => 'spa',
            'country_slug' => 'viet-nam',
            'title' => 'Spa & wellness — gói thư giãn 90 phút',
            'slug' => 'spa-wellness-goi-90-phut',
            'price_from' => 650000,
            'currency' => 'VND',
            'rating' => 4.8,
            'review_count' => 234,
            'is_featured' => false,
            'is_hot_deal' => false,
            'location_label' => 'Đối tác tại Hà Nội, Đà Nẵng, Sài Gòn, Phú Quốc',
            'summary' => 'Gói spa 90 phút — body scrub, massage body và facial — tại spa 4–5 sao đối tác hoặc in-room tại resort (tùy địa điểm).',
            'highlights' => [
                'Spa đối tác chuẩn vệ sinh và dịch vụ',
                'Nguyên liệu tự nhiên — sả, gừng, cà phê',
                'In-room spa tại resort (Phú Quốc, Đà Nẵng)',
                'Đặt lịch linh hoạt 9h–21h',
                'Quà voucher cho khách tour ViTravel',
            ],
            'inclusions' => ['Gói spa 90 phút', 'Đồ uống chào mừng', 'Phí đặt lịch'],
            'exclusions' => ['Tip kỹ thuật viên', 'Vận chuyển đến spa'],
            'notes' => ['Thai massage / hot stone — phụ phí 100–200k.'],
            'attrs' => ['service_type' => 'spa', 'duration_minutes' => 90],
        ],
        [
            'code' => 'other-massage-foot-body',
            'cluster' => 'other',
            'category_slug' => 'massage',
            'country_slug' => 'viet-nam',
            'title' => 'Massage chân & body — 60 phút',
            'slug' => 'massage-chan-body-60-phut',
            'price_from' => 350000,
            'currency' => 'VND',
            'rating' => 4.5,
            'review_count' => 567,
            'is_featured' => false,
            'is_hot_deal' => true,
            'discount_badge' => 'Phổ biến',
            'location_label' => 'Hà Nội, Hội An, Nha Trang, Sài Gòn',
            'summary' => 'Massage truyền thống Việt Nam — xoa bóp chân, vai gáy sau ngày dài đi tour — spa uy tín, không ép tip.',
            'highlights' => [
                'Massage chân + body 60 phút',
                'Spa được ViTravel kiểm duyệt — an toàn, sạch',
                'Không ép mua thêm dịch vụ',
                'Đặt lịch nhanh qua Zalo ViTravel',
                'Giá cố định — không phát sinh',
            ],
            'inclusions' => ['Massage 60 phút', 'Khăn, đồ uống trà'],
            'exclusions' => ['Tip (tuỳ ý)', 'Vận chuyển'],
            'notes' => ['Couple room — đặt trước 24h.'],
            'attrs' => ['service_type' => 'massage', 'duration_minutes' => 60],
        ],
        [
            'code' => 'other-luggage-shipper',
            'cluster' => 'other',
            'category_slug' => 'shipper',
            'country_slug' => 'viet-nam',
            'title' => 'Gửi hành lý — hotel to hotel / airport',
            'slug' => 'gui-hanh-ly-hotel-to-hotel',
            'price_from' => 250000,
            'currency' => 'VND',
            'rating' => 4.6,
            'review_count' => 189,
            'is_featured' => false,
            'is_hot_deal' => false,
            'location_label' => 'Nội thành Hà Nội, Đà Nẵng, Sài Gòn',
            'summary' => 'Gửi vali từ khách sạn này sang khách sạn khác hoặc ra sân bay — đi tour nhẹ tay, không kéo vali cả ngày.',
            'highlights' => [
                'Pickup tại khách sạn — giao đích trong 24h',
                'Tracking qua SMS/Zalo',
                'Bảo hiểm hàng hoá cơ bản',
                'Hỗ trợ gửi ra sân bay trước chuyến bay',
                'Vali 20–30 kg — phụ phí vali lớn',
            ],
            'inclusions' => ['Gửi 1 vali ≤20 kg', 'Tracking', 'Bảo hiểm cơ bản'],
            'exclusions' => ['Vali quá cân', 'Gửi ngoại thành', 'Đồ dễ vỡ không đóng gói'],
            'notes' => ['Đặt trước 12h so với giờ pickup.'],
            'attrs' => ['service_type' => 'luggage_shipping', 'max_weight_kg' => 20],
        ],
        [
            'code' => 'other-private-guide',
            'cluster' => 'other',
            'category_slug' => 'huong-dan-vien',
            'country_slug' => 'viet-nam',
            'title' => 'Hướng dẫn viên riêng — tiếng Anh / Pháp / Nhật',
            'slug' => 'huong-dan-vien-rieng-da-ngon-ngu',
            'price_from' => 1500000,
            'currency' => 'VND',
            'rating' => 4.9,
            'review_count' => 312,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Hà Nội, Huế, Hội An, Sài Gòn, Phú Quốc',
            'summary' => 'HDV riêng thẻ hành nghề — dẫn city tour, di sản, ẩm thực đường phố — linh hoạt lịch trình, không ghép đoàn.',
            'highlights' => [
                'HDV thẻ quốc tế TCHQ / địa phương',
                'Tiếng Anh, Pháp, Nhật, Hàn (theo yêu cầu)',
                '8 giờ/ngày — overtime báo trước',
                'Am hiểu lịch sử, ẩm thực, chụp ảnh',
                'Phù hợp gia đình và VIP cần riêng tư',
            ],
            'inclusions' => ['HDV 8 giờ', 'Phí dịch vụ ViTravel'],
            'exclusions' => ['Vé tham quan', 'Ăn uống HDV', 'Xe (thuê riêng)'],
            'notes' => ['Tết và lễ — phụ phí 20–30%.'],
            'attrs' => ['service_type' => 'private_guide', 'languages' => ['en', 'fr', 'ja', 'ko']],
            'options' => [
                ['code' => 'guide-en', 'name' => 'HDV tiếng Anh', 'price_from' => 1500000],
                ['code' => 'guide-fr', 'name' => 'HDV tiếng Pháp', 'price_from' => 1800000],
            ],
        ],
        [
            'code' => 'other-medical-assistance',
            'cluster' => 'other',
            'category_slug' => 'y-te',
            'country_slug' => 'viet-nam',
            'title' => 'Hỗ trợ y tế du lịch — tư vấn & đặt lịch bệnh viện',
            'slug' => 'ho-tro-y-te-du-lich',
            'price_from' => 500000,
            'currency' => 'VND',
            'rating' => 4.8,
            'review_count' => 87,
            'is_featured' => false,
            'is_hot_deal' => false,
            'location_label' => 'Toàn quốc — đối tác bệnh viện quốc tế',
            'summary' => 'Tư vấn y tế khi du lịch — kết nối phòng khám quốc tế, dịch thuật y khoa và đặt lịch khám nhanh tại Hà Nội, Đà Nẵng, Sài Gòn.',
            'highlights' => [
                'Hotline tư vấn y tế tiếng Anh/Việt',
                'Đặt lịch bệnh viện quốc tế (Vinmec, FV, Family Medical)',
                'Dịch thuật viên y tế đi cùng (optional)',
                'Hỗ trợ mua thuốc và telemedicine',
                'Phối hợp bảo hiểm du lịch nếu có',
            ],
            'inclusions' => ['Tư vấn & đặt lịch', 'Phí dịch vụ coordination'],
            'exclusions' => ['Chi phí khám chữa bệnh', 'Thuốc', 'Cấp cứu vận chuyển'],
            'notes' => ['Không thay thế cấp cứu 115 — gọi 115 khi nguy hiểm tính mạng.'],
            'attrs' => ['service_type' => 'medical_assistance'],
        ],
        [
            'code' => 'other-emergency-support-247',
            'cluster' => 'other',
            'category_slug' => 'khan-cap',
            'country_slug' => 'viet-nam',
            'title' => 'Hỗ trợ khẩn cấp 24/7 — hotline ViTravel',
            'slug' => 'ho-tro-khan-cap-24-7',
            'price_from' => 0,
            'currency' => 'VND',
            'rating' => 5.0,
            'review_count' => 156,
            'is_featured' => true,
            'is_hot_deal' => false,
            'location_label' => 'Toàn quốc — 24 giờ / 7 ngày',
            'summary' => 'Đường dây nóng hỗ trợ khách tour ViTravel — mất hộ chiếu, tai nạn, hủy chuyến đột xuất, hỗ trợ pháp lý cơ bản. Miễn phí cho khách đặt tour qua ViTravel.',
            'highlights' => [
                'Hotline 24/7 — tiếng Việt & tiếng Anh',
                'Hỗ trợ báo mất giấy tờ, hướng dẫn thủ tục',
                'Phối hợp cấp cứu và bệnh viện',
                'Hỗ trợ đổi lịch tour/hotel khi force majeure',
                'Miễn phí cho booking tour ViTravel — liên hệ để biết điều kiện',
            ],
            'inclusions' => ['Hotline 24/7', 'Coordination cơ bản'],
            'exclusions' => ['Chi phí thay thế dịch vụ', 'Luật sư', 'Vận chuyển y tế'],
            'notes' => ['Giá hiển thị "liên hệ" — dịch vụ miễn phí cho khách tour.', 'Số hotline gửi trong voucher tour.'],
            'attrs' => ['service_type' => 'emergency_support', 'availability' => '24/7', 'price_label' => 'Liên hệ'],
            'faqs' => [
                ['q' => 'Ai được dùng hotline miễn phí?', 'a' => 'Khách đã đặt và thanh toán tour hoặc combo dịch vụ qua ViTravel — số hotline in trên voucher xác nhận.'],
            ],
        ],
    ],

    'service_listing_faqs' => [
        [
            'q' => 'Giá "từ" trên trang dịch vụ có phải giá cố định không?',
            'a' => 'Không — giá "từ" là mức tham khảo theo mùa thấp điểm hoặc loại tiêu chuẩn. ViTravel báo giá chính xác sau khi nhận ngày sử dụng, số lượng khách và yêu cầu cụ thể, trước khi bạn thanh toán.',
        ],
        [
            'q' => 'Tôi có thể kết hợp nhiều dịch vụ (vé tàu + khách sạn + tour) trong một đơn không?',
            'a' => 'Có. ViTravel thiết kế itinerary tùy chỉnh — gộp vé tàu/máy bay, lưu trú, vé vui chơi và dịch vụ hỗ trợ vào một báo giá minh bạch, một đầu mối chăm sóc.',
        ],
        [
            'q' => 'Chính sách hoàn/hủy dịch vụ lẻ khác tour trọn gói như thế nào?',
            'a' => 'Mỗi loại dịch vụ tuân theo điều kiện nhà cung cấp (hãng bay, resort, công viên…). ViTravel ghi rõ điều kiện hoàn trên báo giá và voucher — thường vé tàu/máy bay và vé công viên khó hoàn hơn dịch vụ spa hoặc thuê xe.',
        ],
        [
            'q' => 'ViTravel có bán vé máy bay và vé tàu trực tiếp trên website không?',
            'a' => 'Website hiển thị tham khảo và form yêu cầu báo giá (lead-gen). Sau khi bạn gửi yêu cầu, tư vấn viên xác nhận chỗ, giá và gửi link thanh toán hoặc hóa đơn — đảm bảo không phí ẩn.',
        ],
        [
            'q' => 'Dịch vụ hỗ trợ khẩn cấp 24/7 áp dụng khi nào?',
            'a' => 'Miễn phí cho khách đã đặt tour hoặc combo qua ViTravel. Hotline hỗ trợ mất giấy tờ, tai nạn, thay đổi lịch trình khẩn cấp và phối hợp cơ quan chức năng — số điện thoại ghi trên voucher xác nhận của bạn.',
        ],
    ],
];
